{{- if .Values.orleans.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "generic.fullname" . }}-pod-reader-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  {{- if and .Values.serviceAccount.name .Values.serviceAccount.enabled  }}
  name: {{ .Values.serviceAccount.name | default "default "}}
  {{- else }}
  name: {{ include "generic.fullname" . | default "default "}}
  {{- end }}
  apiGroup: ''
roleRef:
  kind: Role
  name: {{ include "generic.fullname" . }}-pod-reader
  apiGroup: ''
{{- end }}