apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/part-of: {{ .Chart.Name }} 
  updateStrategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdateMaxUnavailable | default 1 }}
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        checksum/confd: {{ include (print .Template.BasePath "/configmap-confd.yaml") . | sha256sum | trunc 63 }}
        checksum/conf: {{ include (print .Template.BasePath "/configmap-conf.yaml") . | sha256sum | trunc 63 }} 
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ .Release.Name }}
        ports:
        {{- range $k, $v := .Values.services }}
        - containerPort: {{ $v.containerPort }}
          name: {{ $v.name }}
          {{ if eq $v.type "HostPort" }}
          hostPort: {{ $v.hostPort }}
          {{- end }}
        {{- end }}
        {{- range $k, $v := .Values.extraPorts }}
        - containerPort: {{ $v.containerPort }}
          name: {{ $v.name }}
          {{ if eq $v.type "HostPort" }}
          hostPort: {{ $v.hostPort }}
          {{- end }}
        {{- end }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
          {{- if .Values.ssl.enabled }}
          - mountPath: "/etc/nginx/ssh_password_file"
            subPath: "ssh_password_file"
            name: conf
          {{- if .Values.confd.enabled }}
          {{- range $k, $v := .Values.confd.files }}
          - mountPath: "/etc/nginx/certs/{{ $v.ssl_cert_dir_name }}"
            name: {{ $v.ssl_cert_dir_name }}
          {{- end }}
          {{- end }}
          {{- end }}
          - mountPath: "/etc/nginx/conf.d/"
            name: confd
          - mountPath: "/etc/nginx/nginx.conf"
            subPath: "nginx.conf"
            name: conf
          - mountPath: "/usr/share/nginx/html/custom_50x.html"
            subPath: "custom_50x.html"
            name: conf
          - mountPath: "/usr/share/nginx/html/custom_403.html"
            subPath: "custom_403.html"
            name: conf
          - mountPath: "/usr/share/nginx/html/custom_404.html"
            subPath: "custom_404.html"
            name: conf
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5; nginx -c /etc/nginx/nginx.conf -s quit;"]
        {{ if .Values.basicAuth.enabled }}
          postStart:  
            exec:
              command:
                - "sh"
                - "-c"
                - |
                  #!/bin/bash
                  # Install Basic Auth Password and configure htaccess  ;
                  apt update ;
                  apt install -y apache2-utils ;
                  mkdir -p /etc/apache2 ;
                  touch /etc/apache2/.htpasswd
                  {{- range $name, $value := .Values.basicAuth.users }}
                  {{- if not (empty $value)  }}
                  echo {{ $value | quote }} | htpasswd -i /etc/apache2/.htpasswd {{ $name }} ;
                  {{- end }}
                  {{- end }}
                  chown root:root /etc/apache2/.htpasswd ;
          {{ end }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        startupProbe:
{{ toYaml .Values.startupProbe | indent 10 }}
      volumes:
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- if .Values.ssl.enabled }}
      {{- if .Values.confd.enabled }}
      {{- range $k, $v := .Values.confd.files }}
        - secret: 
            defaultMode: 420
            secretName: "{{ $v.ssl_cert_existing_secret_name }}"
          name: {{ $v.ssl_cert_dir_name }}
      {{- end }}
      {{- end }}
      {{- end }}
        - name: conf
          configMap: 
            name: "{{ .Release.Name }}-conf"
            defaultMode: 0777
        - name: confd
          configMap: 
            name: "{{ .Release.Name }}-confd"
            defaultMode: 0777