{{ if .Values.extraPorts }}
{{- range $k, $v := .Values.extraPorts }}
{{ if $v.type }}
apiVersion: v1
kind: Service
metadata:
  {{ if $v.name }}
  name: {{ $.Release.Name }}-{{ $v.name }}
  {{ else }}
  name: {{ $.Release.Name }}
  {{ end }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{ if not (eq $v.type "HostPort") }}
  type: {{ $v.type }}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
  ports:
  - name: {{ $v.name }}
    port: {{ $v.containerPort }}
    targetPort: {{ $v.containerPort }}
    {{ if or (eq $v.type "LoadBalancer") (eq $v.type "NodePort" ) }} {{ if or (eq $v.type "NodePort") ($v.nodePort)}}
    nodePort: {{ $v.nodePort }}
    {{ end }}
    protocol: TCP
{{ end }}
{{ end }}
---
{{- end -}}
{{ end }}