apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample
  name: sample
  namespace: default
spec:
  containers:
  - image: nginx
    name: sample
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: sample