# See ../../charts/ingress-nginx/values.yaml for full list of features

LoadBalancerType: proxy_protocol
whiteListing:
  enabled: false

image:
  name: nginx
  tag: 1.22.0
  pullPolicy: IfNotPresent

services:
  - name: "http" # name "http" binds to http listeners 
    type: NodePort
    nodePort: 30080
    containerPort: 80
  - name: "https" # name "https" binds to https listeners 
    type: NodePort
    nodePort: 30443
    containerPort: 443

rollingUpdateMaxUnavailable: 1 # 1 is the minimum available value for this field when using DaemonSet

configMap:
  enabled: true
  name: frontend-app-nginx-config
  files:
    app.conf: |
      server {
          listen 80;
          
          server_name    worth.cogitogroup.co.uk;

          root /www/data/;

          location / {
              root /www/data/;
            }
          location /news {
              root /www/data/news;
            }

          location /people {
             root /www/data/people
          }
          

          client_max_body_size 100m;



        }

confd:
  enabled: true
  files:
    worth.cogitogroup.co.uk.conf: 
      basicAuth:
        enabled: enabled
        users:
          admin: SomePassWord.
      ssl_cert_dir_name: worth-cogitogroup-co-uk
      ssl_cert_existing_secret_name: worth-cogitogroup-co-uk # contains tls.key and tls.crt 
      server_name: worth.cogitogroup.co.uk
      backend_host: worth.svc.cluster.local
      backend_port: 80
      extraServerProperties: |
        some_server_block_property 10m
      extraLocationPropertiesBegin: |
        proxy_read_timeout      90;
      extraLocationPropertiesFinal: |
        proxy_set_header Authorization ""; # stop nginx forwarding the basic auth header for nginx .htpasswd to backend

ssl:
  enabled: false